# Generated by Django 2.2.28 on 2023-02-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicinedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'medicalmedicines',
            },
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
