# Generated by Django 2.2.28 on 2023-02-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20230216_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicinedetails',
            new_name='medicalmedicine',
        ),
    ]
