# Generated by Django 2.2.28 on 2023-02-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_auto_20230216_1147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='medicalmedicine',
            new_name='medicalmedicines',
        ),
        migrations.AlterModelTable(
            name='medicalmedicines',
            table='medicalmedicines',
        ),
    ]
