# Generated by Django 4.2 on 2023-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_auto_20230216_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalmedicines',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
